package gtl.math.geometry.impl;

import gtl.math.geometry.Envelope;
import gtl.math.geometry.Interval;
import gtl.math.geometry.IntervalType;
import gtl.math.geometry.Vertex;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.Random;

/**
 * Created by ZhenwenHe on 2017/3/15.
 */
public class GeometryImpl {
    public static Interval createInterval(IntervalType t, double low, double high ){
        return new IntervalImpl(t,low,high);
    }
    public static Vertex createVertex(){
        return new VertexImpl();
    }
    public static Vertex createVertex(double [] v){
        return new VertexImpl(v);
    }
    public static Vertex createVertex(double x,double y){
        return new VertexImpl(x,y);
    }
    public static Vertex createVertex(double x,double y,double z){
        return new VertexImpl(x,y,z);
    }
    public static Envelope createEnvelope(){
        return new EnvelopeImpl();
    }
    public static Envelope createEnvelope(double [] low, double [] high){
        return new EnvelopeImpl(low,high);
    }

    /**
     * each interval's range is [0,1.0)
     * @param numb number of the generated intervals
     * @return
     */
    public static Interval[] generateRandomIntervals(int numb){
        double v1, v2,v;
        Interval [] ivs = new Interval[numb];
        Random r = new Random(System.currentTimeMillis());
        for(int i=0;i<numb;i++) {
            v1 = r.nextDouble();
            v2 = r.nextDouble();
            while(v1==v2){
                v2=r.nextDouble();
            }
            if(v1>v2)
                ivs[i]=createInterval(IntervalType.IT_CLOSED,v2,v1);
            else
                ivs[i]=createInterval(IntervalType.IT_CLOSED,v1,v2);
        }
        return ivs;
    }

    /**
     * all vertices generated by this function are in the range [0,1.0)
     * @param numb vertex number
     * @param dim  vertex dimension
     * @return
     */
    public static Vertex[] generateRandomVertices(int numb, int dim){
        double v1, v2,v;
        Vertex [] ivs = new Vertex[numb];
        Random r = new Random(System.currentTimeMillis());
        for(int i=0;i<numb;i++) {
            ivs[i]=createVertex();
            ivs[i].makeDimension(dim);
            for(int k=0;k<dim;k++){
                ivs[i].getCoordinates()[k]=r.nextDouble();
            }
        }
        return ivs;
    }

    /**
     * all envelopes generated by this function are in the range [0,1.0)
     * @param numb
     * @param dim
     * @param minEdgeLength
     * @param maxEdgeLength
     * @return
     */
    public static Envelope[] generateRandomEnvelopes(int numb, int dim, double minEdgeLength,double maxEdgeLength){
        double v1, v2,v;
        Envelope [] ivs = new Envelope[numb];
        double [] originalVertex=new double[dim];
        double [] highVertex=new double[dim];
        double [] delta=new double[dim];//[minEdgeLength,maxEdgeLength]
        Random r = new Random(System.currentTimeMillis());
        for(int i=0;i<numb;i++) {
            for(int k=0;k<dim;k++){
                originalVertex[k]=r.nextDouble();
                delta[k]=r.nextDouble();
                while(delta[k]>maxEdgeLength || delta[k]<minEdgeLength)
                    delta[k]=r.nextDouble();
                highVertex[k]=originalVertex[k]+delta[k];
            }
            ivs[i]=createEnvelope(originalVertex,highVertex);
        }
        return ivs;
    }

    public static boolean writeEnvelopeFile(Envelope[] envelopes, String envelopeFileName){
        try {
            DataOutputStream dos = new DataOutputStream(new FileOutputStream(envelopeFileName));
            dos.writeInt(envelopes.length);
            for(Envelope e: envelopes)
                e.store(dos);
            dos.close();
        }
        catch (Exception e){
            e.printStackTrace();
        }
        return true;
    }
    public static Envelope[] readEnvelopeFile(String envelopeFileName){
        try {
            DataInputStream dis = new DataInputStream(new FileInputStream(envelopeFileName));
            int len = dis.readInt();
            if(len==0) return null;
            Envelope [] envelopes = new Envelope[len];
            for(int i=0;i<len;++i){
                envelopes[i]=createEnvelope();
                envelopes[i].load(dis);
            }
            return envelopes;
        }
        catch (Exception e){
            e.printStackTrace();
            return null;
        }
    }
}
